### ISSUE TITLE
List index out of range in lambda code.

### ISSUE THREAD

**Issue by rohankoushikrv** [aws-samples/amazon-connect-live-agent-translation#2]
Hello, 

[ERROR]	2024-07-24T12:12:59.035Z	09485e66-a1a8-407e-9b5b-898cccad5870	list index out of range
Traceback (most recent call last):
  File "/tmp/crhelper/resource_helper.py", line 204, in _wrap_function
    self.PhysicalResourceId = func(self._event, self._context) if func else ''
  File "/var/task/index.py", line 76, in create
    instance_data["wisdomArn"] = case_domain_integration['IntegrationAssociationSummaryList'][0]['IntegrationArn']
IndexError: list index out of range

Facing issue here.

**Comment by skeretna** [comment]
it's a bug in the code,

in the MultiLingualCC.yaml

change this line:
instance_data["wisdomArn"] = case_domain_integration['IntegrationAssociationSummaryList'][0]['IntegrationArn']

to this line:
instance_data["wisdomArn"] = wisdom_assistant_integration['IntegrationAssociationSummaryList'][0]['IntegrationArn']

and it should work
